apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: caannamalai/springpetclinic #rework this so each SE is building the image to their own repo in a parent registy
  newTag: latest

labels:
- includeSelectors: true
  pairs:
    app: spring-petclinic
